// generated by sv2v
module neuron_learn_layer1 (
	clock,
	valid,
	learn,
	in,
	out,
	weights,
	activation_upper_bound,
	activation_lower_bound,
	expected_out,
	expected_in
);
	parameter N = 16;
	input wire clock;
	input wire valid;
	input wire learn;
	input wire [(N * 16) - 1:0] in;
	output wire [15:0] out;
	output wire [(N * 17) - 1:0] weights;
	output wire [16:0] activation_upper_bound;
	output wire [16:0] activation_lower_bound;
	input wire [15:0] expected_out;
	output wire [(N * 16) - 1:0] expected_in;
	wire [(N * 16) - 1:0] unavg_expected_in;
	unit_arr_average #(
		.N(1),
		.LEN(N)
	) avg(
		.in(unavg_expected_in),
		.out(expected_in)
	);
	neuron_learn #(.N(N)) instance0(
		.clock(clock),
		.valid(valid),
		.learn(learn),
		.in(in),
		.out(out[0+:16]),
		.weights(weights[0+:17 * N]),
		.activation_upper_bound(activation_upper_bound[0+:17]),
		.activation_lower_bound(activation_lower_bound[0+:17]),
		.expected_out(expected_out[0+:16]),
		.expected_in(unavg_expected_in[0+:16 * N])
	);
endmodule
